<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Seed sample cosmetic products.
     */
    public function run(): void
    {
        $products = [
            // LIPSTIK (16)
            [
                'name' => 'Wardah Everyday Matte Lip Shot',
                'description' => 'Lip cream matte instan dengan tekstur ringan dan hasil warna yang intens sekali oles.',
                'price' => 39000,
                'stock' => 50,
                'sku' => 'WARD-LIP-SHOT-001',
                'weight' => 15,
                'brand_name' => 'Wardah',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Wardah Velvet Matte Lip Mousse',
                'description' => 'Lip mousse dengan formula velvet powdery yang lembut dan tidak lengket di bibir.',
                'price' => 65000,
                'stock' => 40,
                'sku' => 'WARD-VELVET-MOUSSE-001',
                'weight' => 15,
                'brand_name' => 'Wardah',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Wardah Colorfit Last All Day Lip Paint',
                'description' => 'Liquid lip transferproof dengan ketahanan hingga 12 jam dan warna yang nyata.',
                'price' => 58000,
                'stock' => 60,
                'sku' => 'WARD-COLORFIT-PAINT-001',
                'weight' => 15,
                'brand_name' => 'Wardah',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Wardah Exclusive Matte Lip Cream',
                'description' => 'Lip cream dengan pigmentasi tinggi dan kandungan vitamin E untuk menjaga kelembapan bibir.',
                'price' => 52000,
                'stock' => 55,
                'sku' => 'WARD-EXCL-LIPCREAM-001',
                'weight' => 20,
                'brand_name' => 'Wardah',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Wardah Glasting Liquid Lip',
                'description' => 'Produk pewarna bibir dengan hasil akhir kilau glasting yang tahan lama dan tidak transfer.',
                'price' => 79000,
                'stock' => 35,
                'sku' => 'WARD-GLASTING-LIP-001',
                'weight' => 20,
                'brand_name' => 'Wardah',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Maybelline Superstay Matte Ink',
                'description' => 'Liquid lipstick matte transferproof nomor 1 di Indonesia dengan ketahanan hingga 16 jam.',
                'price' => 110000,
                'stock' => 80,
                'sku' => 'MAYB-SS-MATTE-001',
                'weight' => 25,
                'brand_name' => 'Maybelline',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Maybelline Superstay Vinyl Ink',
                'description' => 'Tint bibir dengan hasil akhir berkilau (vinyl) yang tahan lama dan tahan transfer.',
                'price' => 125000,
                'stock' => 70,
                'sku' => 'MAYB-SS-VINYL-001',
                'weight' => 25,
                'brand_name' => 'Maybelline',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Maybelline Sensational Liquid Matte',
                'description' => 'Lip cream matte yang nyaman dan ringan dipakai sehari-hari tanpa membuat bibir kering.',
                'price' => 65000,
                'stock' => 90,
                'sku' => 'MAYB-SENS-LIQUID-001',
                'weight' => 20,
                'brand_name' => 'Maybelline',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Maybelline Lifter Gloss',
                'description' => 'Lip gloss dengan hyaluronic acid untuk bibir tampak lebih penuh, lembap, dan berkilau alami.',
                'price' => 145000,
                'stock' => 30,
                'sku' => 'MAYB-LIFTER-GLOSS-001',
                'weight' => 30,
                'brand_name' => 'Maybelline',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Emina Creamytint',
                'description' => 'Lip tint dengan tekstur creamy yang lembut dan melembapkan dengan warna manis yang tahan lama.',
                'price' => 42000,
                'stock' => 65,
                'sku' => 'EMIN-CREAMYTINT-001',
                'weight' => 15,
                'brand_name' => 'Emina',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Emina Glossy Stain',
                'description' => 'Lip tint dengan hasil akhir glossy yang cantik tanpa terasa berminyak di bibir.',
                'price' => 45000,
                'stock' => 50,
                'sku' => 'EMIN-GLOSSY-STAIN-001',
                'weight' => 15,
                'brand_name' => 'Emina',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Emina Magic Potion Lip Tint',
                'description' => 'Lip tint cair berpigmentasi tinggi dengan formula transferproof dan smudgeproof.',
                'price' => 38000,
                'stock' => 75,
                'sku' => 'EMIN-MAGIC-POTION-001',
                'weight' => 15,
                'brand_name' => 'Emina',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Emina Watercolor Lip Serum',
                'description' => 'Serum bibir berwarna yang menutrisi sekaligus mencerahkan bibir gelap.',
                'price' => 40000,
                'stock' => 45,
                'sku' => 'EMIN-WATERCOLOR-SERUM-001',
                'weight' => 15,
                'brand_name' => 'Emina',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'L\'Oréal Paris Rouge Signature',
                'description' => 'Liquid lipstick matte ultra-ringan dengan pigmentasi intens tahan hingga 24 jam.',
                'price' => 135000,
                'stock' => 40,
                'sku' => 'LORE-ROUGE-SIGN-001',
                'weight' => 25,
                'brand_name' => "L'Oréal",
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Pixy Matte in Love Lipstick',
                'description' => 'Lipstik matte dengan warna nyata sekali pulas serta diperkaya vitamin E.',
                'price' => 38000,
                'stock' => 50,
                'sku' => 'PIXY-MATTE-LOVE-001',
                'weight' => 20,
                'brand_name' => 'Pixy',
                'category_name' => 'Lipstik',
            ],
            [
                'name' => 'Implora Urban Cream Matte',
                'description' => 'Lip cream matte termurah dan berkualitas tinggi dengan warna-warna trendy yang memukau.',
                'price' => 22000,
                'stock' => 120,
                'sku' => 'IMPL-URBAN-MATTE-001',
                'weight' => 15,
                'brand_name' => 'Implora',
                'category_name' => 'Lipstik',
            ],

            // SKINCARE (20)
            [
                'name' => 'Wardah Hydrating Toner',
                'description' => 'Toner pelembab dengan kandungan hyaluronic acid yang membantu menjaga kelembaban kulit.',
                'price' => 89000,
                'stock' => 50,
                'sku' => 'WARD-HYDRA-TONER-001',
                'weight' => 100,
                'brand_name' => 'Wardah',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Wardah Pure Brightening Mask',
                'description' => 'Masker wajah dengan kandungan ekstrak mawar dan vitamin E untuk kulit yang lebih cerah.',
                'price' => 78000,
                'stock' => 55,
                'sku' => 'WARD-BRIGHT-MASK-001',
                'weight' => 100,
                'brand_name' => 'Wardah',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Wardah Lightening Day Cream',
                'description' => 'Krim siang pencerah yang melembapkan kulit sekaligus melindunginya dari sinar UV dan blue light.',
                'price' => 45000,
                'stock' => 60,
                'sku' => 'WARD-LIGHT-CREAM-001',
                'weight' => 80,
                'brand_name' => 'Wardah',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Wardah C-Defense Serum',
                'description' => 'Serum wajah dengan konsentrat vitamin C tinggi untuk mencerahkan dan melindungi dari radikal bebas.',
                'price' => 75000,
                'stock' => 45,
                'sku' => 'WARD-CDEF-SERUM-001',
                'weight' => 50,
                'brand_name' => 'Wardah',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Wardah UV Shield Essential Sunscreen',
                'description' => 'Sunscreen SPF 35 PA+++ bertekstur gel cair yang ringan dan bebas alkohol.',
                'price' => 35000,
                'stock' => 100,
                'sku' => 'WARD-UV-SHIELD-001',
                'weight' => 60,
                'brand_name' => 'Wardah',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Wardah Crystal Secret Dark Spot Corrector',
                'description' => 'Serum khusus untuk menyamarkan noda hitam bekas jerawat dan meratakan warna kulit.',
                'price' => 95000,
                'stock' => 35,
                'sku' => 'WARD-CRYSTAL-CORR-001',
                'weight' => 50,
                'brand_name' => 'Wardah',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Wardah Acnederm Pore Blackhead Balm',
                'description' => 'Balm lembut untuk membersihkan komedo membandel dan meredakan jerawat aktif.',
                'price' => 38000,
                'stock' => 40,
                'sku' => 'WARD-ACNE-BALM-001',
                'weight' => 40,
                'brand_name' => 'Wardah',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Emina Sea Bright Serum',
                'description' => 'Serum terang dengan vitamin C yang membantu mencerahkan dan meremajakan kulit.',
                'price' => 65000,
                'stock' => 40,
                'sku' => 'EMIN-BRIGHT-SERUM-001',
                'weight' => 50,
                'brand_name' => 'Emina',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Emina Bright Stuff Face Wash',
                'description' => 'Pembersih wajah harian dengan ekstrak summer plum untuk kulit tampak lebih cerah alami.',
                'price' => 25000,
                'stock' => 85,
                'sku' => 'EMIN-BRIGHT-WASH-001',
                'weight' => 100,
                'brand_name' => 'Emina',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Emina Skin Buddy Micellar Water',
                'description' => 'Pembersih makeup cair lembut dengan ekstrak calendula, aman untuk kulit sensitif.',
                'price' => 28000,
                'stock' => 70,
                'sku' => 'EMIN-MICELLAR-WATER-001',
                'weight' => 120,
                'brand_name' => 'Emina',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Emina Sun Battle SPF 30',
                'description' => 'Sunscreen ringan dengan proteksi SPF 30 PA+++ dan ekstrak lidah buaya yang menyegarkan.',
                'price' => 32000,
                'stock' => 90,
                'sku' => 'EMIN-SUN-BATTLE-001',
                'weight' => 80,
                'brand_name' => 'Emina',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Emina Ms. Pimple Acne Solution Spot Gel',
                'description' => 'Gel totol jerawat transparan yang mempercepat penyembuhan tanpa meninggalkan bekas.',
                'price' => 34000,
                'stock' => 50,
                'sku' => 'EMIN-ACNE-SPOT-001',
                'weight' => 30,
                'brand_name' => 'Emina',
                'category_name' => 'Skincare',
            ],
            [
                'name' => "L'Oréal Paris Revitalift Anti-Aging Moisturizer",
                'description' => 'Krim anti-aging dengan teknologi revitalift untuk mengurangi garis halus dan kerutan.',
                'price' => 165000,
                'stock' => 35,
                'sku' => 'LOREAL-REVITA-CREAM-001',
                'weight' => 80,
                'brand_name' => "L'Oréal",
                'category_name' => 'Skincare',
            ],
            [
                'name' => "L'Oréal Paris Glycolic-Bright Serum",
                'description' => 'Serum dengan konsentrasi optimal Glycolic Acid untuk mencerahkan noda hitam secara instan.',
                'price' => 185000,
                'stock' => 30,
                'sku' => 'LOREAL-GLYCOLIC-SERUM-001',
                'weight' => 50,
                'brand_name' => "L'Oréal",
                'category_name' => 'Skincare',
            ],
            [
                'name' => "L'Oréal Paris UV Defender Sunscreen",
                'description' => 'Sunscreen premium anti-aging yang memberikan proteksi maksimal dari sinar UVA/UVB.',
                'price' => 145000,
                'stock' => 45,
                'sku' => 'LOREAL-UV-DEFENDER-001',
                'weight' => 60,
                'brand_name' => "L'Oréal",
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Pixy UV Essentials Daily Sunscreen SPF 32',
                'description' => 'Sunscreen ringan yang melindungi kulit dari sinar UV dan cocok untuk penggunaan sehari-hari.',
                'price' => 45000,
                'stock' => 60,
                'sku' => 'PIXY-UV-ESSENTIALS-001',
                'weight' => 60,
                'brand_name' => 'Pixy',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Pixy White Aqua Gel Cream',
                'description' => 'Krim pelembap pagi dengan water-based formula yang memberikan hidrasi dingin menyegarkan.',
                'price' => 58000,
                'stock' => 40,
                'sku' => 'PIXY-AQUA-GEL-001',
                'weight' => 50,
                'brand_name' => 'Pixy',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Implora Pearl Serum Moisturizer',
                'description' => 'Serum pelembab dengan ekstrak mutiara yang memberikan nutrisi dan kelembaban maksimal.',
                'price' => 55000,
                'stock' => 45,
                'sku' => 'IMPL-PEARL-SERUM-001',
                'weight' => 50,
                'brand_name' => 'Implora',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Implora Luminous Brightening Serum',
                'description' => 'Serum pencerah wajah dengan 10% Niacinamide dan Kakadu Plum untuk mencerahkan noda hitam.',
                'price' => 35000,
                'stock' => 110,
                'sku' => 'IMPL-BRIGHT-SERUM-001',
                'weight' => 40,
                'brand_name' => 'Implora',
                'category_name' => 'Skincare',
            ],
            [
                'name' => 'Implora Acne Serum',
                'description' => 'Serum khusus jerawat dengan Salicylic Acid dan Centella Asiatica untuk meredakan inflamasi.',
                'price' => 35000,
                'stock' => 95,
                'sku' => 'IMPL-ACNE-SERUM-001',
                'weight' => 40,
                'brand_name' => 'Implora',
                'category_name' => 'Skincare',
            ],

            // FOUNDATION (15)
            [
                'name' => 'Wardah Colorfit Matte Foundation',
                'description' => 'Foundation cair dengan SPF 30 PA+++ yang memberikan hasil matte dan menyatu alami di kulit.',
                'price' => 72000,
                'stock' => 50,
                'sku' => 'WARD-COLORFIT-FDN-001',
                'weight' => 40,
                'brand_name' => 'Wardah',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Wardah Exclusive Liquid Foundation',
                'description' => 'Alas bedak cair yang memberikan coverage tinggi dan memudarkan ketidaksempurnaan wajah.',
                'price' => 85000,
                'stock' => 45,
                'sku' => 'WARD-EXCL-FDN-001',
                'weight' => 45,
                'brand_name' => 'Wardah',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Wardah Lightening Liquid Foundation',
                'description' => 'Foundation cair ringan dengan micronized bright pigment untuk mencerahkan kulit wajah.',
                'price' => 55000,
                'stock' => 55,
                'sku' => 'WARD-LIGHT-FDN-001',
                'weight' => 40,
                'brand_name' => 'Wardah',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Wardah Colorfit Perfect Glow Cushion',
                'description' => 'Cushion ber-coverage medium-to-full yang memberikan kilau alami sepanjang hari.',
                'price' => 115000,
                'stock' => 40,
                'sku' => 'WARD-COLORFIT-CUSH-001',
                'weight' => 50,
                'brand_name' => 'Wardah',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Maybelline Fit Me Matte + Poreless Foundation',
                'description' => 'Liquid foundation legendaris dengan formula ultra-lightweight dan penahan minyak berlebih.',
                'price' => 149000,
                'stock' => 80,
                'sku' => 'MAYB-FITME-MATTE-001',
                'weight' => 50,
                'brand_name' => 'Maybelline',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Maybelline Superstay Active Wear Foundation',
                'description' => 'Foundation dengan ketahanan ekstrem hingga 30 jam, tahan keringat dan tahan transfer.',
                'price' => 229000,
                'stock' => 35,
                'sku' => 'MAYB-SS-ACTIVE-001',
                'weight' => 50,
                'brand_name' => 'Maybelline',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Maybelline Fit Me Tinted Moisturizer',
                'description' => 'Pelembap berwarna dengan perlindungan ringan yang melembapkan hingga 12 jam.',
                'price' => 125000,
                'stock' => 45,
                'sku' => 'MAYB-FITME-TINT-001',
                'weight' => 45,
                'brand_name' => 'Maybelline',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Emina Bare With Me Mineral Mild Foundation',
                'description' => 'Foundation dengan formula ramah kulit sensitif, hasil akhir semi-matte alami.',
                'price' => 79000,
                'stock' => 35,
                'sku' => 'EMIN-BARE-FDN-001',
                'weight' => 40,
                'brand_name' => 'Emina',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Emina City Chic CC Cream',
                'description' => 'Color corrector cream yang meratakan warna kulit dan melembapkan dalam satu langkah.',
                'price' => 55000,
                'stock' => 50,
                'sku' => 'EMIN-CHIC-CC-001',
                'weight' => 40,
                'brand_name' => 'Emina',
                'category_name' => 'Foundation',
            ],
            [
                'name' => "L'Oréal Paris Infallible 24H Matte Cover Foundation",
                'description' => 'Foundation tahan lama 24 jam dengan coverage maksimal dan hasil akhir velvet matte.',
                'price' => 199000,
                'stock' => 40,
                'sku' => 'LORE-INFAL-MATTE-001',
                'weight' => 55,
                'brand_name' => "L'Oréal",
                'category_name' => 'Foundation',
            ],
            [
                'name' => "L'Oréal Paris True Match Liquid Foundation",
                'description' => 'Foundation dengan teknologi pencocokan warna kulit yang presisi dan hidrasi 24 jam.',
                'price' => 219000,
                'stock' => 30,
                'sku' => 'LORE-TRUEMATCH-001',
                'weight' => 55,
                'brand_name' => "L'Oréal",
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Pixy UV Whitening Stay Last Liquid Foundation',
                'description' => 'Liquid foundation ringan berformula water-based untuk tata rias halus bebas kilap.',
                'price' => 65000,
                'stock' => 50,
                'sku' => 'PIXY-STAY-LAST-001',
                'weight' => 45,
                'brand_name' => 'Pixy',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Pixy Make It Glow Dewy Cushion',
                'description' => 'Cushion dengan daya tutup tinggi yang memberikan efek dewy/glowing mewah ala Korea.',
                'price' => 125000,
                'stock' => 40,
                'sku' => 'PIXY-GLOW-CUSH-001',
                'weight' => 50,
                'brand_name' => 'Pixy',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Implora Even Seamless Liquid Foundation',
                'description' => 'Foundation cair ringan dengan hasil mulus seperti kulit kedua, menyamarkan pori-pori.',
                'price' => 52000,
                'stock' => 85,
                'sku' => 'IMPL-SEAMLESS-FDN-001',
                'weight' => 40,
                'brand_name' => 'Implora',
                'category_name' => 'Foundation',
            ],
            [
                'name' => 'Implora Airbrush Cushion',
                'description' => 'Cushion dengan puff khusus yang menghasilkan riasan wajah merata bagai sapuan airbrush.',
                'price' => 75000,
                'stock' => 60,
                'sku' => 'IMPL-AIRBRUSH-CUSH-001',
                'weight' => 50,
                'brand_name' => 'Implora',
                'category_name' => 'Foundation',
            ],

            // MASKARA (10)
            [
                'name' => 'Wardah EyeXpert Volume Expert Mascara',
                'description' => 'Maskara dengan lash precision brush untuk menebalkan bulu mata secara instan dan rapi.',
                'price' => 75000,
                'stock' => 50,
                'sku' => 'WARD-EYEXPERT-VOL-001',
                'weight' => 25,
                'brand_name' => 'Wardah',
                'category_name' => 'Maskara',
            ],
            [
                'name' => 'Wardah EyeXpert Perfect Curl Mascara',
                'description' => 'Maskara pelentik bulu mata tahan air dengan kandungan vitamin untuk bulu mata sehat.',
                'price' => 68000,
                'stock' => 45,
                'sku' => 'WARD-EYEXPERT-CURL-001',
                'weight' => 25,
                'brand_name' => 'Wardah',
                'category_name' => 'Maskara',
            ],
            [
                'name' => 'Maybelline Lash Sensational Sky High Mascara',
                'description' => 'Maskara viral yang menghasilkan bulu mata super panjang, tebal, dan terangkat kuat dari akar.',
                'price' => 140000,
                'stock' => 90,
                'sku' => 'MAYB-SKY-HIGH-001',
                'weight' => 30,
                'brand_name' => 'Maybelline',
                'category_name' => 'Maskara',
            ],
            [
                'name' => 'Maybelline The Colossal Mascara',
                'description' => 'Menebalkan bulu mata 9x lipat dengan formula kolagen pembangun volume instan.',
                'price' => 110000,
                'stock' => 75,
                'sku' => 'MAYB-COLOSSAL-001',
                'weight' => 30,
                'brand_name' => 'Maybelline',
                'category_name' => 'Maskara',
            ],
            [
                'name' => 'Maybelline Hypercurl Mascara',
                'description' => 'Maskara waterproof terlaris yang menjaga bulu mata tetap lentik hingga 36 jam lamanya.',
                'price' => 75000,
                'stock' => 150,
                'sku' => 'MAYB-HYPERCURL-001',
                'weight' => 25,
                'brand_name' => 'Maybelline',
                'category_name' => 'Maskara',
            ],
            [
                'name' => 'Emina Star Lash Mascara',
                'description' => 'Maskara bening/hitam transparan untuk mempercantik bulu mata remaja agar tampak natural.',
                'price' => 55000,
                'stock' => 50,
                'sku' => 'EMIN-STAR-LASH-001',
                'weight' => 20,
                'brand_name' => 'Emina',
                'category_name' => 'Maskara',
            ],
            [
                'name' => "L'Oréal Paris Lash Paradise Mascara",
                'description' => 'Maskara legendaris dunia yang menghasilkan volume ekstra tebal dan bulu mata selembut sutra.',
                'price' => 159000,
                'stock' => 65,
                'sku' => 'LORE-LASH-PARADISE-001',
                'weight' => 30,
                'brand_name' => "L'Oréal",
                'category_name' => 'Maskara',
            ],
            [
                'name' => "L'Oréal Paris Voluminous Lash Paradise Waterproof",
                'description' => 'Formula tahan air dari Lash Paradise untuk ketahanan mutlak terhadap air, keringat, dan minyak.',
                'price' => 169000,
                'stock' => 40,
                'sku' => 'LORE-VOLUM-LASH-001',
                'weight' => 30,
                'brand_name' => "L'Oréal",
                'category_name' => 'Maskara',
            ],
            [
                'name' => 'Pixy Waterproof Mascara',
                'description' => 'Maskara dengan sikat lurus klasik untuk memanjangkan bulu mata secara natural dan awet.',
                'price' => 48000,
                'stock' => 60,
                'sku' => 'PIXY-WATERPROOF-MASC-001',
                'weight' => 25,
                'brand_name' => 'Pixy',
                'category_name' => 'Maskara',
            ],
            [
                'name' => 'Implora Deep Black Mascara',
                'description' => 'Maskara hitam pekat berharga ekonomis dengan sikat aplikator melengkung untuk pelentikan optimal.',
                'price' => 28000,
                'stock' => 100,
                'sku' => 'IMPL-DEEP-BLACK-MASC-001',
                'weight' => 20,
                'brand_name' => 'Implora',
                'category_name' => 'Maskara',
            ],

            // EYESHADOW (10)
            [
                'name' => 'Wardah Exclusive Eyeshadow Palette',
                'description' => 'Palet eyeshadow mewah dengan kombinasi warna komplit untuk riasan natural hingga glamor.',
                'price' => 95000,
                'stock' => 35,
                'sku' => 'WARD-EXCL-EYESH-001',
                'weight' => 50,
                'brand_name' => 'Wardah',
                'category_name' => 'Eyeshadow',
            ],
            [
                'name' => 'Wardah Colorfit Quad Eyeshadow',
                'description' => 'Palet mini 4 warna serbaguna dengan kombinasi warna komplementer matte dan shimmer.',
                'price' => 75000,
                'stock' => 40,
                'sku' => 'WARD-COLOR-QUAD-001',
                'weight' => 40,
                'brand_name' => 'Wardah',
                'category_name' => 'Eyeshadow',
            ],
            [
                'name' => 'Wardah Instaperfect Spotlight Chromatic Eyeshadow',
                'description' => 'Eyeshadow premium berpigmentasi tinggi dengan 10 pilihan warna dramatis bernuansa mewah.',
                'price' => 150000,
                'stock' => 25,
                'sku' => 'WARD-INSTA-SPOT-001',
                'weight' => 60,
                'brand_name' => 'Wardah',
                'category_name' => 'Eyeshadow',
            ],
            [
                'name' => 'Maybelline The Nudes Eyeshadow Palette',
                'description' => '12 pilihan warna nude natural legendaris Maybelline untuk padu padan tak terbatas.',
                'price' => 199000,
                'stock' => 45,
                'sku' => 'MAYB-NUDES-PALETTE-001',
                'weight' => 80,
                'brand_name' => 'Maybelline',
                'category_name' => 'Eyeshadow',
            ],
            [
                'name' => 'Maybelline City Mini Palette',
                'description' => 'Palet mini 6 warna yang terinspirasi dari gemerlap malam kota New York.',
                'price' => 145000,
                'stock' => 50,
                'sku' => 'MAYB-CITY-MINI-001',
                'weight' => 45,
                'brand_name' => 'Maybelline',
                'category_name' => 'Eyeshadow',
            ],
            [
                'name' => 'Emina Pop Rouge Eyeshadow',
                'description' => 'Kombinasi 3 warna manis dalam 1 wadah mungil, cocok untuk pemula dan penggunaan harian.',
                'price' => 48000,
                'stock' => 55,
                'sku' => 'EMIN-POP-ROUGE-001',
                'weight' => 30,
                'brand_name' => 'Emina',
                'category_name' => 'Eyeshadow',
            ],
            [
                'name' => 'Emina Eye Do Shadow',
                'description' => 'Eyeshadow bertekstur lembut dengan formulasi warna yang mudah dibaurkan secara halus.',
                'price' => 52000,
                'stock' => 40,
                'sku' => 'EMIN-EYE-DO-SHAD-001',
                'weight' => 30,
                'brand_name' => 'Emina',
                'category_name' => 'Eyeshadow',
            ],
            [
                'name' => "L'Oréal Paris La Petite Palette",
                'description' => 'Palet eyeshadow ultra-pigmented berukuran mini dengan tekstur velvet yang mulus.',
                'price' => 185000,
                'stock' => 30,
                'sku' => 'LORE-PETITE-PALETTE-001',
                'weight' => 40,
                'brand_name' => "L'Oréal",
                'category_name' => 'Eyeshadow',
            ],
            [
                'name' => 'Pixy 3-in-1 Shade Eyeshadow',
                'description' => '3 warna bergradasi pas untuk membuat efek mata lebih dalam dan hidup seketika.',
                'price' => 45000,
                'stock' => 50,
                'sku' => 'PIXY-3IN1-EYESH-001',
                'weight' => 35,
                'brand_name' => 'Pixy',
                'category_name' => 'Eyeshadow',
            ],
            [
                'name' => 'Implora Eyeshadow Palette',
                'description' => 'Palet eyeshadow terjangkau dengan warna-warni memikat untuk riasan ekspresif.',
                'price' => 38000,
                'stock' => 90,
                'sku' => 'IMPL-EYESH-PALETTE-001',
                'weight' => 60,
                'brand_name' => 'Implora',
                'category_name' => 'Eyeshadow',
            ],

            // BLUSH ON (10)
            [
                'name' => 'Wardah Colorfit Cream Blush',
                'description' => 'Blush on bertekstur krim-ke-bubuk yang melebur halus menghasilkan rona pipi berseri.',
                'price' => 54000,
                'stock' => 45,
                'sku' => 'WARD-CREAM-BLUSH-001',
                'weight' => 25,
                'brand_name' => 'Wardah',
                'category_name' => 'Blush On',
            ],
            [
                'name' => 'Wardah Exclusive Blush On',
                'description' => 'Pewarna pipi padat dengan microcoated particle untuk kehalusan dan ketahanan riasan.',
                'price' => 49000,
                'stock' => 50,
                'sku' => 'WARD-EXCL-BLUSH-001',
                'weight' => 30,
                'brand_name' => 'Wardah',
                'category_name' => 'Blush On',
            ],
            [
                'name' => 'Maybelline Fit Me Blush',
                'description' => 'Blush on berpigmen tinggi dengan formula selembut mentega yang mudah menyatu di pipi.',
                'price' => 99000,
                'stock' => 65,
                'sku' => 'MAYB-FITME-BLUSH-001',
                'weight' => 35,
                'brand_name' => 'Maybelline',
                'category_name' => 'Blush On',
            ],
            [
                'name' => 'Maybelline Cheek Heat Gel-Cream Blush',
                'description' => 'Blush on gel berbasis air untuk warna pipi dewy natural seperti bersemu dari dalam.',
                'price' => 110000,
                'stock' => 40,
                'sku' => 'MAYB-CHEEK-HEAT-001',
                'weight' => 30,
                'brand_name' => 'Maybelline',
                'category_name' => 'Blush On',
            ],
            [
                'name' => 'Emina Cheek Lit Cream Blush',
                'description' => 'Krim perona pipi legendaris remaja dengan teknologi color-changing menyesuaikan pH kulit.',
                'price' => 33000,
                'stock' => 80,
                'sku' => 'EMIN-CHEEKLIT-CREAM-001',
                'weight' => 25,
                'brand_name' => 'Emina',
                'category_name' => 'Blush On',
            ],
            [
                'name' => 'Emina Cheek Lit Pressed Blush',
                'description' => 'Blush on bubuk padat praktis dengan pilihan warna ceria untuk menyegarkan penampilan.',
                'price' => 40000,
                'stock' => 60,
                'sku' => 'EMIN-CHEEKLIT-PRESS-001',
                'weight' => 30,
                'brand_name' => 'Emina',
                'category_name' => 'Blush On',
            ],
            [
                'name' => "L'Oréal Paris Le Bar A Blush",
                'description' => 'Pewarna pipi premium beraroma bunga mawar lembut dengan ketahanan sepanjang hari.',
                'price' => 165000,
                'stock' => 30,
                'sku' => 'LORE-LE-BAR-BLUSH-001',
                'weight' => 40,
                'brand_name' => "L'Oréal",
                'category_name' => 'Blush On',
            ],
            [
                'name' => 'Pixy Twin Blush',
                'description' => 'Perona pipi multifungsi 2-in-1 yang bisa digunakan sebagai blush on sekaligus pewarna bibir.',
                'price' => 52000,
                'stock' => 50,
                'sku' => 'PIXY-TWIN-BLUSH-001',
                'weight' => 25,
                'brand_name' => 'Pixy',
                'category_name' => 'Blush On',
            ],
            [
                'name' => 'Implora Cheek & Liptint',
                'description' => 'Cairan multifungsi untuk bibir dan pipi agar tampak segar merona sepanjang waktu.',
                'price' => 22000,
                'stock' => 150,
                'sku' => 'IMPL-CHEEK-LIPTINT-001',
                'weight' => 20,
                'brand_name' => 'Implora',
                'category_name' => 'Blush On',
            ],
            [
                'name' => 'Implora Urban Blush On',
                'description' => 'Blush on ekonomis dengan pigmen halus, memperindah struktur pipi dalam sekejap.',
                'price' => 28000,
                'stock' => 85,
                'sku' => 'IMPL-URBAN-BLUSH-001',
                'weight' => 30,
                'brand_name' => 'Implora',
                'category_name' => 'Blush On',
            ],

            // PARFUM (10)
            [
                'name' => 'Wardah Scentsation Eau De Toilette Joyful',
                'description' => 'Wewangian manis buah persik dan cokelat yang memancarkan energi ceria nan manis.',
                'price' => 55000,
                'stock' => 40,
                'sku' => 'WARD-SCENT-JOY-001',
                'weight' => 120,
                'brand_name' => 'Wardah',
                'category_name' => 'Parfum',
            ],
            [
                'name' => 'Wardah Scentsation Eau De Toilette Peaceful',
                'description' => 'Aroma menenangkan buah anggur dan musk yang memberikan ketenangan jiwa sepanjang hari.',
                'price' => 55000,
                'stock' => 35,
                'sku' => 'WARD-SCENT-PEACE-001',
                'weight' => 120,
                'brand_name' => 'Wardah',
                'category_name' => 'Parfum',
            ],
            [
                'name' => 'Wardah Scentsation Eau De Toilette Passion',
                'description' => 'Wangi jeruk mandarin dan pear segar yang melambangkan semangat dan dinamisme diri.',
                'price' => 55000,
                'stock' => 45,
                'sku' => 'WARD-SCENT-PASS-001',
                'weight' => 120,
                'brand_name' => 'Wardah',
                'category_name' => 'Parfum',
            ],
            [
                'name' => 'Wardah Scentsation Eau De Toilette Bliss',
                'description' => 'Kombinasi bunga mawar putih dan melati untuk keharuman floral klasik nan feminin.',
                'price' => 55000,
                'stock' => 50,
                'sku' => 'WARD-SCENT-BLISS-001',
                'weight' => 120,
                'brand_name' => 'Wardah',
                'category_name' => 'Parfum',
            ],
            [
                'name' => 'Wardah Scentsation Body Mist Purity',
                'description' => 'Body mist penyegar tubuh beraroma bersih dan segar seperti sehabis mandi air dingin.',
                'price' => 38000,
                'stock' => 60,
                'sku' => 'WARD-SCENT-PURE-001',
                'weight' => 150,
                'brand_name' => 'Wardah',
                'category_name' => 'Parfum',
            ],
            [
                'name' => 'Emina Body Mist Rainforest',
                'description' => 'Penyegar tubuh dengan aroma hutan basah dan dedaunan hijau yang alami menyegarkan.',
                'price' => 28000,
                'stock' => 50,
                'sku' => 'EMIN-MIST-RAIN-001',
                'weight' => 100,
                'brand_name' => 'Emina',
                'category_name' => 'Parfum',
            ],
            [
                'name' => 'Emina Body Mist Ocean Breeze',
                'description' => 'Aroma laut bebas yang sejuk dan menenangkan, cocok untuk temani hari aktifmu.',
                'price' => 28000,
                'stock' => 55,
                'sku' => 'EMIN-MIST-OCEAN-001',
                'weight' => 100,
                'brand_name' => 'Emina',
                'category_name' => 'Parfum',
            ],
            [
                'name' => 'Pixy Cologne Gel',
                'description' => 'Cologne bertekstur gel transparan dingin yang memberikan keharuman instan bebas lengket.',
                'price' => 20000,
                'stock' => 80,
                'sku' => 'PIXY-COLOGNE-GEL-001',
                'weight' => 80,
                'brand_name' => 'Pixy',
                'category_name' => 'Parfum',
            ],
            [
                'name' => 'Implora Eau De Parfum',
                'description' => 'Keharuman mewah eksklusif dari Implora dengan daya tahan semerbak yang luar biasa.',
                'price' => 45000,
                'stock' => 70,
                'sku' => 'IMPL-EDP-001',
                'weight' => 120,
                'brand_name' => 'Implora',
                'category_name' => 'Parfum',
            ],
            [
                'name' => "L'Oréal Paris Men Expert Barber Club Fragrance",
                'description' => 'Aroma kayu aras (cedarwood) yang maskulin dan berkelas khas salon cukur premium pria.',
                'price' => 245000,
                'stock' => 25,
                'sku' => 'LORE-MEN-BARBER-001',
                'weight' => 150,
                'brand_name' => "L'Oréal",
                'category_name' => 'Parfum',
            ],

            // PERAWATAN RAMBUT (10)
            [
                'name' => 'Wardah Hairfall Treatment Shampoo',
                'description' => 'Sampo kaya nutrisi tanaman untuk memperkuat akar rambut dan meminimalkan rontok.',
                'price' => 32000,
                'stock' => 80,
                'sku' => 'WARD-HAIRFALL-SHAMP-001',
                'weight' => 200,
                'brand_name' => 'Wardah',
                'category_name' => 'Perawatan Rambut',
            ],
            [
                'name' => 'Wardah Anti Dandruff Shampoo',
                'description' => 'Formula aktif tea tree oil untuk mengusir ketombe membandel dan gatal di kulit kepala.',
                'price' => 32000,
                'stock' => 75,
                'sku' => 'WARD-ANTIDANDRUFF-001',
                'weight' => 200,
                'brand_name' => 'Wardah',
                'category_name' => 'Perawatan Rambut',
            ],
            [
                'name' => 'Wardah Nutri Shine Shampoo',
                'description' => 'Menghidupkan kembali kilau rambut kusam dan kering akibat paparan panas matahari.',
                'price' => 32000,
                'stock' => 65,
                'sku' => 'WARD-NUTRISHINE-001',
                'weight' => 200,
                'brand_name' => 'Wardah',
                'category_name' => 'Perawatan Rambut',
            ],
            [
                'name' => 'Wardah Hair Conditioner',
                'description' => 'Kondisioner pelengkap pembersih rambut untuk menjaga batang rambut tetap halus terurai.',
                'price' => 28000,
                'stock' => 70,
                'sku' => 'WARD-HAIR-COND-001',
                'weight' => 180,
                'brand_name' => 'Wardah',
                'category_name' => 'Perawatan Rambut',
            ],
            [
                'name' => "L'Oréal Paris Extraordinary Oil",
                'description' => 'Serum minyak rambut multifungsi terlaris untuk kelembutan, kilau, dan perlindungan rambut.',
                'price' => 145000,
                'stock' => 50,
                'sku' => 'LORE-EXTRA-OIL-001',
                'weight' => 100,
                'brand_name' => "L'Oréal",
                'category_name' => 'Perawatan Rambut',
            ],
            [
                'name' => "L'Oréal Paris Total Repair 5 Shampoo",
                'description' => 'Mengatasi 5 tanda kerusakan rambut utama: patah, kering, kusam, kasar, dan bercabang.',
                'price' => 48000,
                'stock' => 100,
                'sku' => 'LORE-TOTAL-REPAIR-001',
                'weight' => 250,
                'brand_name' => "L'Oréal",
                'category_name' => 'Perawatan Rambut',
            ],
            [
                'name' => "L'Oréal Paris Elseve Color Protect Shampoo",
                'description' => 'Sampo khusus rambut diwarnai untuk menjaga kecerahan warna agar bertahan lebih lama.',
                'price' => 52000,
                'stock' => 80,
                'sku' => 'LORE-COLOR-PROTECT-001',
                'weight' => 250,
                'brand_name' => "L'Oréal",
                'category_name' => 'Perawatan Rambut',
            ],
            [
                'name' => "L'Oréal Paris Fall Resist 3X Shampoo",
                'description' => 'Memberi nutrisi menyeluruh dari akar hingga ujung rambut guna mengurangi patah rontok.',
                'price' => 48000,
                'stock' => 90,
                'sku' => 'LORE-FALL-RESIST-001',
                'weight' => 250,
                'brand_name' => "L'Oréal",
                'category_name' => 'Perawatan Rambut',
            ],
            [
                'name' => "L'Oréal Paris Extraordinary Oil Steam Mask",
                'description' => 'Masker rambut canggih dengan teknologi pemanas otomatis layaknya spa rambut profesional.',
                'price' => 58000,
                'stock' => 40,
                'sku' => 'LORE-OIL-STEAM-001',
                'weight' => 80,
                'brand_name' => "L'Oréal",
                'category_name' => 'Perawatan Rambut',
            ],
            [
                'name' => 'Implora Hair Color',
                'description' => 'Pewarna rambut instan praktis dengan aneka pilihan warna menarik, aman dan wangi.',
                'price' => 35000,
                'stock' => 30,
                'sku' => 'IMPL-HAIR-COLOR-001',
                'weight' => 150,
                'brand_name' => 'Implora',
                'category_name' => 'Perawatan Rambut',
            ],
        ];

        foreach ($products as $productData) {
            $brand = Brand::where('name', $productData['brand_name'])->first();
            
            if (!$brand) {
                $this->command->warn("Brand '{$productData['brand_name']}' not found. Skipping product '{$productData['name']}'");
                continue;
            }

            $category = Category::where('name', $productData['category_name'])->first();

            if (!$category) {
                $this->command->warn("Category '{$productData['category_name']}' not found. Skipping product '{$productData['name']}'");
                continue;
            }

            Product::firstOrCreate(
                ['sku' => $productData['sku']],
                [
                    'brand_id' => $brand->id,
                    'category_id' => $category->id,
                    'name' => $productData['name'],
                    'slug' => Str::slug($productData['name']),
                    'description' => $productData['description'],
                    'price' => $productData['price'],
                    'stock' => $productData['stock'],
                    'sku' => $productData['sku'],
                    'weight' => $productData['weight'],
                    'is_active' => true,
                    'average_rating' => fake()->randomFloat(1, 3, 5),
                ]
            );
        }

        $this->command->info(count($products) . ' products seeded.');
    }
}
